// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXyeuPWbaMFhvoVtbM6dhVgB2Q_jFwKI',
    appId: '1:492301705094:web:0c5b5d4570fabdc9405607',
    messagingSenderId: '492301705094',
    projectId: 'flutterworkoutapp',
    authDomain: 'flutterworkoutapp.firebaseapp.com',
    storageBucket: 'flutterworkoutapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWSVzaDq-rdbswQQFpA7ay2ELCQYjbm8',
    appId: '1:492301705094:android:5154dabbad7dc586405607',
    messagingSenderId: '492301705094',
    projectId: 'flutterworkoutapp',
    storageBucket: 'flutterworkoutapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqnhdw3uGVI1_YOt-UYjYo0_1MUs2XdQ',
    appId: '1:492301705094:ios:a744b1139fa1c635405607',
    messagingSenderId: '492301705094',
    projectId: 'flutterworkoutapp',
    storageBucket: 'flutterworkoutapp.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqnhdw3uGVI1_YOt-UYjYo0_1MUs2XdQ',
    appId: '1:492301705094:ios:4758953001bfd747405607',
    messagingSenderId: '492301705094',
    projectId: 'flutterworkoutapp',
    storageBucket: 'flutterworkoutapp.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
